services:
  backend-api:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: recipio-backend-api
    ports:
      - "8081:80"

    environment:     
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development} 
      - ASPNETCORE_URLS=http://+:80;
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - JWT_KEY=${JWT_KEY} 
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}        

    depends_on:
      db:
        condition: service_healthy

    volumes:
      - ./app_logs:/app/logs 

  db:
    container_name: recipio-postgres-db
    image: postgres:15
    restart: always
    ports:
      - "5433:5432" 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}      
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5


